meta_product_name: "tripstr"
meta_title: "tripstr - hassle-free city trips"
meta_description: "With tripstr's custom routes, you spend less time planning and more time actually enjoying your city trips. Picking the best sights for a day trip has never been easier."
meta_image: "cover.png"
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
